version: '3'

services:

  visualizer:
    build:
      context: .
      dockerfile: visualizer/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - localhost

  app:
    build: .
    ports:
      - "5555:5555"
    networks:
      - localhost

networks:
  localhost: